### ISSUE TITLE
Yarn nor NPM seem to be reflecting latest changes

### ISSUE THREAD

**Issue by david-bermudez1102** [cryptocoinjs/eckey#18]
Hey everyone. Thank you for having updated the repo. I was struggling to get it to work when I updated my electron version, but I was able to find out your latest pr. 

Is there anyway the version can be updated to 1.0.1 so that yarn recognizes it? if I run `yarn install eckey` it just downloads the regular package 1.0, without the latest changes.

If I run `yarn add https://github.com/cryptocoinjs/eckey  ` it does download the updated code, but since another package depends on 1.0.0 it becomes a mess. Thank you!

**Comment by junderw** [comment]
The latest changes have been published as 1.0.1
